// Copyright (c) 2018 The GAM Authors 

#ifndef INCLUDE_SETTINGS_H_
#define INCLUDE_SETTINGS_H_

using namespace std;
#define UNDER_DEVELOPMENT
//#define DEBUG
//#define LOCAL_MEMORY_HOOK

//#define NDEBUG

#define HARDWARE_CACHE_LINE 64

/*
 * test switch
 */
//#define WH_USE_LOCK
//#define USE_LRU
#define USE_PIPE_W_TO_H
#define USE_PIPE_H_TO_W
//#define USE_BOOST_QUEUE
//#define USE_BUF_ONLY

//#define USE_HUGEPAGE

#ifdef USE_PIPE_H_TO_W
#define USE_LOCAL_TIME_EVENT
#endif

#define MAX_SHARED_LOCK 254 //MAX(unsigned char)-1
#define EXCLUSIVE_LOCK_TAG 255 //MAX(unsigned char)

#define BLOCK_POWER 9
#define BLOCK_MASK 0xFFFFFFFFFFFFFE00L
#define BLOCK_SIZE (1 << BLOCK_POWER)

#define RDMA_RESOURCE_EXCEPTION 1
#define RDMA_CONTEXT_EXCEPTION 2
#define SERVER_NOT_EXIST_EXCEPTION 3
#define SERVER_ALREADY_EXIST_EXCEPTION 4

#define MIN_RESERVED_FDS 32
#define EVENTLOOP_FDSET_INCR (MIN_RESERVED_FDS+96)
#define EVENTLOOP_FDSET_INCR (MIN_RESERVED_FDS+96)

#define TCP_BACKLOG       511     /* TCP listen backlog */
#define IP_STR_LEN 46 /* INET6_ADDRSTRLEN is 46, but we need to be sure */

#define MAX_CQ_EVENTS 1024

#define MAX_NUM_WORKER 20
#define MAX_MASTER_PENDING_MSG 512
#define MAX_UNSIGNALED_MSG 256

#define MAX_WORKER_PENDING_MSG 512 
#define MASTER_RDMA_SRQ_RX_DEPTH \
    (MAX_MASTER_PENDING_MSG * MAX_NUM_WORKER)
#define WORKER_RDMA_SRQ_RX_DEPTH \
    (MAX_WORKER_PENDING_MSG * (MAX_NUM_WORKER-1) + MAX_MASTER_PENDING_MSG)

#define MAX_REQUEST_SIZE 8192
#define WORKER_BUFFER_SIZE (MAX_WORKER_PENDING_MSG * MAX_REQUEST_SIZE)
#define MASTER_BUFFER_SIZE (MAX_MASTER_PENDING_MSG * MAX_REQUEST_SIZE)

#define MAX_IPPORT_STRLEN 21 //192.168.154.154:12345
#define MAX_WORKERS_STRLEN (MAX_NUM_WORKER*MAX_IPPORT_STRLEN+MAX_NUM_WORKER-1)  //192.168.154.154:12345,

#define INIT_WORKQ_SIZE 2000

#define MAX_MEM_STATS_SIZE  43 //8+16+16+3

#endif /* INCLUDE_SETTINGS_H_ */
